### ISSUE TITLE
loss of video quality when using plugin

### ISSUE THREAD

**Issue by timbiker** [WowzaMediaSystems/wse-plugin-avmix#2]
Hello, 
this plugin is very interesting for me as we are doing multilingual live streaming for my church.
However when I try it I get a loss of quality.
my attempts where made by streaming a file multiple times with ffmpeg in separate stream and gathering audio and video again with the plugin, the ffmpeg command used to live stream to wowza is the following:

ffmpeg -re -i test.mp4 -map 0:v -codec copy -copyts -f rtsp rtsp://127.0.0.1:1937/Live_localsource/video1 -map 0:a -c
odec copy -copyts -f rtsp rtsp://127.0.0.1:1937/Live_localsource/audio1 -map 0:a -codec copy -copyts -f rtsp rtsp://1
27.0.0.1:1937/Live_localsource/audio2 -map 0:v -map 0:a -codec copy -copyts -f rtsp rtsp://127.0.0.1:1937/Live_locals
ource/videoaudio

the plugin remix the video1 and audio1 together into avmix1.
If I play the videoaudio stream I get perfect video but if I play the avmix1 I get video artefacts. (using the test rtmp player).

the video file test.mp4 I use shows following codec information.
  Duration: 02:36:06.62, start: 0.000000, bitrate: 2261 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 2057 kb/s, 50 fps, 50 tbr, 16k tbn, 100 tbc (default)
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 194 kb/s (default)

Would you have any clue why it impacts the video quality ?

Rgds

**Comment by rogerlittin** [comment]
Hi,

Because you are using RTSP, you may be getting some packet loss or out of order packets that is affecting the mixed stream more that it affects the separate streams. Try switching your stream type to RTMP.  You can also enable the debug logging in the avmix module to see what is going wrong. Look for cases where there are large bursts of data from one source or the other, which could cause a buffer overflow or underrun. If this is the case, adjusting the sort delay may help.

If you're still having issues, can you please open a support ticket, and we will need to see the server conf files and log files since the last restart that show the problem occuring. Ideally, perform a fresh restart and test before sending the logs.  If possible, can you also send us a link to download a source file that can be used to test with.

Thanks,

Roger.

**Comment by timbiker** [comment]
Thanks for the very fast answer.
I have not looked at the logs yet but switching to rtmp indeed seem to solve it;

Thanks !!!
